services:
  transaction-evaluator:
    build:
      context: ./ms-transaction-evaluator
    volumes:
      - ./ms-transaction-evaluator:/app:cached
      - /app/build
    env_file:
      - .env
    ports:
      - "${EVALUATOR_APP_PORT}:${EVALUATOR_APP_PORT}"
    environment:
      - GO111MODULE=on
